version: '3'

services:
  seed:
    image: akka.clusterpingpong:latest
    hostname: seed
    environment:
      CLUSTER_PORT: 4053
      CLUSTER_IP: "seed"
      CLUSTER_SEEDS: "akka.tcp://ClusterSys@seed:4053"
      
  participants:
    image: akka.clusterpingpong:latest
    environment:
      CLUSTER_PORT: 4053
      CLUSTER_SEEDS: "akka.tcp://ClusterSys@seed:4053"
    depends_on:
        - "seed"